### PR TITLE
alpha test

### PR DESCRIPTION
**Pull request by imhta**
[Preview](https://cssgridy.imhta.now.sh)

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @imhtapm, 
This is a collaborative project, please why are you working alone ?
Great Job working alone......
Just few things to do you are to use different media query screen sizes.
Here is the checklist for your project from Microverse project guidelines.
- To consider the project 'complete' it must satisfy the following points:
## General
- [x] The project has a descriptive README.md
#### Grid
The CSS files define:
* [x] A class that represents a row
* [x] Classes to define columns sized from 1/12th of the row to 100% of the row
* [x] The defined columns should have breakpoints (example column-large-2)
## Responsiveness
##### Breakpoints
* [x] The CSS files should define a breakpoint for small screens with a width of up to 720px
* [x] The CSS files should define a breakpoint for medium screens with a width in the range of 720px - 1024px
* [x] The CSS files should define a breakpoint for large screens with width above 1024px
#### Box utilities
##### Margins
* [x] The CSS files define separate classes for margin top, bottom, left, right, all margins and auto
* [x] The margins should span from `0 rem` to `1 rem`
* [x] The margins should have breakpoints (e.g. margin-sm-top-1)


**After fixing the _**unchecked**_ issues and validation errors please send another request to re-review this project.**

**Comment by imhta** [comment]
I don't have a partner, because he temporarily steps out of microverse due to his health. that's why I work alone

**Comment by bellom** [comment]
Ok, what a great work you did all alone 👍.

**Comment by Torres-ssf** [comment]
### Nicely done @imhtapm 
You sure created an awesome framework. I'm going to give this project a 👍. You can merge to master and submit the form.

**Pull request merged**
